# Linear Algebra - Worksheet

In [1]:
import numpy as np

In [76]:
# assign variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])
u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])
w = np.array([[1],[8],[0],[5]])

## Matrix Dimensions 

### 1.1)

In [77]:
# dimension of matrix A
np.shape(A)

(2, 3)

### 1.2)

In [78]:
# dimension of matrix B
np.shape(B)

(2, 2)

### 1.3)

In [79]:
# dimension of matrix C
np.shape(C)

(3, 2)

### 1.4)

In [80]:
# dimension of matrix D
np.shape(D)

(2, 3)

### 1.5)

In [81]:
# dimension of vector u
np.shape(u)

(4,)

### 1.6)

In [82]:
# dimension of vector w
np.shape(w)

(4, 1)

## Vector Operations

### 2.1)

In [83]:
# u + v
np.add(u,v)

array([ 9,  7, -4,  9])

### 2.2)

In [84]:
# u - v
np.subtract(u,v)

array([ 3, -3, -2,  1])

### 2.3)

In [85]:
# alpha x u
alpha = 6
np.multiply(alpha,u)

array([ 36,  12, -18,  30])

### 2.4)

In [86]:
# u  v
np.dot(u,v)

51

### 2.5)

In [87]:
# length of u
np.linalg.norm(u)

8.6023252670426267

## Matrix Operations

### 3.1)

In [88]:
# A + C
np.add(A,C)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### 3.2)

In [89]:
# A + C(transpose)
np.subtract(A,np.transpose(C))

array([[-4, -7, -3],
       [ 3,  6,  4]])

### 3.3)

In [90]:
# C(transpose) + 3D
np.add(np.transpose(C),np.multiply(3,D))

array([[14,  3,  3],
       [ 2,  7,  9]])

### 3.4)

In [98]:
# BA
np.matmul(B,A)

array([[-1, -5, -1],
       [ 2,  7,  4]])

### 3.5)

In [59]:
# B.A(transpose)
np.multiply(B,np.transpose(A))

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

## Optional

### 3.6)

In [101]:
# BC
np.multiply(B,C)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

### 3.7)

In [102]:
# CB
np.matmul(C,B)

array([[ 5, -6],
       [ 9, -8],
       [ 6, -6]])

### 3.8)

In [95]:
# B^^4
np.linalg.matrix_power(B,4)

array([[ 1, -4],
       [ 0,  1]])

### 3.9)

In [103]:
# A.A(transpose)
np.matmul(A,np.transpose(A))

array([[14, 28],
       [28, 69]])

### 3.10)

In [104]:
# D(transpose).D
np.matmul(np.transpose(D),D)

array([[10, -4,  0],
       [-4,  8,  8],
       [ 0,  8, 10]])